### ISSUE TITLE
Getting No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)

### ISSUE THREAD

**Issue by parveenb1** [NGDATA/hbase-indexer#103]
Hello,

We have setup solr 6.6 with SSL and Kerberos enable 
our hbase and zookeeper is also kerberos enabled

our hbase-indexer-site.xml file 
====
<configuration>

<property>
  <name>hbaseindexer.zookeeper.connectstring</name>
  <value>zk1:2181,zk2:2181,zk3:2181</value>
</property>
<property>
  <name>hbase.zookeeper.quorum</name>
  <value>zk1,zk2,zk3</value>
</property>
<property>
    <name>hbaseindexer.authentication.type</name>
    <value>kerberos</value>
  </property>
  <property>
    <name>hbaseindexer.authentication.kerberos.keytab</name>
    <value>/hbase/conf/hbase.keytab</value>
  </property>
  <property>
    <name>hbaseindexer.authentication.kerberos.principal</name>
    <value>hbase/_HOST@company</value>
  </property>
  <property>
    <name>hbaseindexer.authentication.kerberos.name.rules</name>
   <value>DEFAULT</value>
  </property>
</configuration>
====
But Getting That error when we put the data in hbase table and it replicate on solr

====== Hbase indexer logs====

17/09/27 15:44:51 DEBUG zookeeper.ClientCnxn: Got ping response for sessionid: 0x35ea5945a99002d after 68ms
17/09/27 15:44:53 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x35ea5945a99002e, packet:: clientPath:null serverPath:null finished:false header:: 19,8  replyHeader:: 19,77309542811,0  request:: '/hbase,F  response:: v{'replication,'meta-region-server,'rs,'splitWAL,'backup-masters,'table-lock,'flush-table-proc,'region-in-transition,'online-snapshot,'acl,'master,'running,'recovering-regions,'tokenauth,'draining,'namespace,'hbaseid,'table} 
17/09/27 15:44:53 DEBUG zookeeper.ClientCnxn: Got ping response for sessionid: 0x35ea5945a99002e after 69ms
17/09/27 15:44:53 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x35ea5945a99002e, packet:: clientPath:null serverPath:null finished:false header:: 20,4  replyHeader:: 20,77309542811,0  request:: '/hbase/meta-region-server,F  response:: #ffffffff0001a726567696f6e7365727665723a313630323031ffffff9f666afffffff8fffffff5ffffff81fffffff150425546a1ca106d3131322e7365727665722e656d627310ffffff947d18ffffff9bffffffa8ffffffebffffffefffffffe72b100183,s{77309411569,77309411569,1505352186793,1505352186793,0,0,0,0,69,0,77309411569} 
17/09/27 15:44:53 WARN ipc.AbstractRpcClient: Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/09/27 15:44:53 ERROR ipc.AbstractRpcClient: SASL authentication failed. The most likely cause is missing or invalid credentials. Consider 'kinit'.
javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
	at org.apache.hadoop.hbase.security.HBaseSaslRpcClient.saslConnect(HBaseSaslRpcClient.java:179)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupSaslConnection(RpcClientImpl.java:609)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.access$600(RpcClientImpl.java:154)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection$2.run(RpcClientImpl.java:735)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection$2.run(RpcClientImpl.java:732)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupIOstreams(RpcClientImpl.java:732)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:885)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:854)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1170)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:213)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:287)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:32651)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:201)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:180)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:369)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:343)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)

**Comment by ascotmoss** [comment]
I have same issue, as hbase indexer is an ongoing service, using keytab would be better manually using kinit.  By the way, I have also tried to use kinit, but the hbase indexer is still not able to read hbase (hbase meta). Please help !

**Comment by salemba** [comment]
I was able to run Hbase-indexer in a kerberized env. One thing I remember, which is not documented anywhere: I had to add another property to the hbase-site.xml I took from my remote hbase server:
    <property>
      <name>**hadoop**.security.authentication</name>
      <value>kerberos</value>
    </property>

What you have inside hbase-site.xml, is 
   <property>
      <name>**hbase**.security.authentication</name>
      <value>kerberos</value>
    </property>

Also, could you please tell how do you start your hbase indexer (start-hbase.sh alone won't work).
