### ISSUE TITLE
Error trying to assign a subscription to index myindexer   when adding indexer

### ISSUE THREAD

**Issue by siliconer** [NGDATA/hbase-indexer#60]
**environment**:  hbase-0.98 ,solr 4.2.0, zookeeper 3.4.5

**procedure**:
following the wiki page,  I have configure the .xml files and start solr in cloud mode,
when executing './bin/hbase-indexer add-indexer -n myindexer -c indexdemo-indexer.xml  -cp solr.zk=localhost:2181/solr -cp solr.collection=collection1', problem occurs.

**problem**:
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/hadoop/libexec/../lib/native/Linux-amd64-64
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:os.version=3.8.0-35-generic
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:user.name=tokyo
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/tokyo
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/tokyo/hbase-indexer-1.6-SNAPSHOT/bin
15/02/02 19:33:11 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=localhost sessionTimeout=30000 watcher=com.ngdata.hbaseindexer.util.zookeeper.StateWatchingZooKeeper$MyWatcher@1505bd58
15/02/02 19:33:11 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
15/02/02 19:33:11 INFO zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
15/02/02 19:33:11 INFO zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14b0cb348b20082, negotiated timeout = 30000
15/02/02 19:33:11 INFO zookeeper.StateWatchingZooKeeper: ZooKeeper session ID is 0x14b0cb348b20082
15/02/02 19:33:12 INFO zookeeper.LeaderElection: Elected as leader for the position of Indexer Master
15/02/02 19:33:12 INFO master.IndexerMaster: Starting up as indexer master.
15/02/02 19:33:12 INFO master.IndexerMaster: Startup as indexer master successful.
15/02/02 19:33:12 INFO mortbay.log: Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
2015-2-2 19:33:12 com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  com/ngdata/hbaseindexer/rest
2015-2-2 19:33:12 com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO:Root resource classes found:
  class com.ngdata.hbaseindexer.rest.IndexerResource
2015-2-2 19:33:12 com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO:Provider classes found:
  class com.ngdata.hbaseindexer.rest.IndexerDefinitionMessageBodyWriter
  class com.ngdata.hbaseindexer.rest.IndexerDefinitionsMessageBodyWriter
15/02/02 19:33:12 INFO mortbay.log: jetty-6.1.26.cloudera.2
**15/02/02 19:33:13 ERROR master.IndexerMaster: Error trying to assign a subscription to index myindexer**
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:131)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:55)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:182)
	at org.apache.hadoop.security.UserGroupInformation.initUGI(UserGroupInformation.java:252)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:223)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:214)
	at org.apache.hadoop.security.UserGroupInformation.isSecurityEnabled(UserGroupInformation.java:277)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:668)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:573)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.hadoop.hbase.util.Methods.call(Methods.java:37)
	at org.apache.hadoop.hbase.security.User.call(User.java:590)
	at org.apache.hadoop.hbase.security.User.callStatic(User.java:580)
	at org.apache.hadoop.hbase.security.User.access$400(User.java:51)
	at org.apache.hadoop.hbase.security.User$SecureHadoopUser.<init>(User.java:397)
	at org.apache.hadoop.hbase.security.User$SecureHadoopUser.<init>(User.java:392)
	at org.apache.hadoop.hbase.security.User.getCurrent(User.java:140)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionKey.<init>(HConnectionManager.java:435)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:180)
	at org.apache.hadoop.hbase.client.replication.ReplicationAdmin.<init>(ReplicationAdmin.java:83)
	at com.ngdata.sep.impl.SepModelImpl.addSubscriptionSilent(SepModelImpl.java:76)
	at com.ngdata.sep.impl.SepModelImpl.addSubscription(SepModelImpl.java:69)
	at com.ngdata.hbaseindexer.master.IndexerMaster.assignSubscription(IndexerMaster.java:244)
	at com.ngdata.hbaseindexer.master.IndexerMaster.access$1300(IndexerMaster.java:78)
	at com.ngdata.hbaseindexer.master.IndexerMaster$EventWorker.run(IndexerMaster.java:575)
	at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	... 28 more
Caused by: java.lang.UnsatisfiedLinkError: org.apache.hadoop.security.JniBasedUnixGroupsMapping.anchorNative()V
	at org.apache.hadoop.security.JniBasedUnixGroupsMapping.anchorNative(Native Method)
	at org.apache.hadoop.security.JniBasedUnixGroupsMapping.<clinit>(JniBasedUnixGroupsMapping.java:49)
	at org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback.<init>(JniBasedUnixGroupsMappingWithFallback.java:38)
	... 33 more
2015-2-2 19:33:13 com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.17 01/17/2013 03:31 PM'
2015-2-2 19:33:14 com.sun.jersey.spi.inject.Errors processErrorMessages
WARN: The following warnings have been detected with resource and/or provider classes:
  WARNING: A sub-resource method, public void com.ngdata.hbaseindexer.rest.IndexerResource.index(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception, with URI template, "", is treated as a resource method
15/02/02 19:33:14 INFO mortbay.log: Started SelectChannelConnector@0.0.0.0:11060

**Comment by gabrielreid** [comment]
This looks to be an environment issue. Could you say what you're using in terms of operating system and JDK version? Are the hbase, solr, and zookeeper parts of a CDH release, or something else?

**Comment by siliconer** [comment]
thanks for your reply.

**Java/OS** 
java version "1.7.0_51"
OpenJDK Runtime Environment (IcedTea 2.4.4) (7u51-2.4.4-0ubuntu0.13.04.2)
OpenJDK 64-Bit Server VM (build 24.45-b08, mixed mode)

** **
as to hbase/solr/zookeeper, I  just downloaded these component on apache.

**Comment by siliconer** [comment]
Now i am trying to use the hbase and zookeper of  CDH4.2 release ,
thanks.

**Comment by siliconer** [comment]
after migrating hbase/zookeeper to CDH4.2 relase, problem solved.
thanks .

**Comment by monodeep12** [comment]
I am getting the same error. Can you please confirm if my versions are correct ?

HBase Version : 0.94.21
Hadoop Version : 1.0.4
Zookeeper Version : 3.4.5

**Comment by finch0001** [comment]
qwe
