### ISSUE TITLE
HBase Indexer to work with Apache HBase

### ISSUE THREAD

**Issue by kanav-narula** [NGDATA/hbase-indexer#64]
I am getting the below error while building with Apache Hbase on running the below mail 

##### `mvn -e clean install -DskipTests -Dhbase.api=0.98`

```
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: null:akuma:jar:1.9

Reason: Cannot find parent: org.kohsuke:pom for project: null:akuma:jar:1.9 for project null:akuma:jar:1.9


[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.kohsuke:akuma:jar': Cannot find parent: org.kohsuke:pom for project: null:akuma:jar:1.9 for project null:akuma:jar:1.9
  org.kohsuke:akuma:jar:1.9

from the specified remote repositories:
  default (http://repo1.maven.org/maven2),
  central (http://repo1.maven.org/maven2),
  cdh.repo.snapshots (https://repository.cloudera.com/artifactory/cloudera-repos/),
  ngdata.oss-releases (http://mvnrepo.ngdata.com/content/repositories/oss-releases)

Path to dependency: 
	1) com.ngdata:hbase-indexer-server:jar:1.6-SNAPSHOT


	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:711)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.kohsuke:akuma:jar': Cannot find parent: org.kohsuke:pom for project: null:akuma:jar:1.9 for project null:akuma:jar:1.9
  org.kohsuke:akuma:jar:1.9
```

Thanks in advance.

**Comment by gabrielreid** [comment]
I just tried running this on a (mostly) blank maven repository and it worked for me. 

Could you post some info on your setup? Particularly, which version of Java are you using, and which version of Maven?

Could you also post the log output from where maven first starts trying to download the org.kohsuke.* artifacts?

Also, do you have any custom settings in your ~/.m2/settings.xml file? For example, are you possibly using a maven proxy or something like that?

**Comment by kanav-narula** [comment]
I am using 4 machines each of 4 GB RAM. 

#####`Versions`
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.7.0_72

Deep down in the logs, i found these errors which came when i run the above command.

**Comment by gabrielreid** [comment]
I'm guessing that this has to do with the version of Maven that you're using -- Maven 2.2.1 was released over 6 years ago, and Maven 3.x has been the generally used version for about 3 years now. 

Could you try building with Maven 3.x?

The number of machines or amount of RAM that you're using shouldn't have any effect here.

**Comment by kanav-narula** [comment]
It worked with maven 3.3.3 
Thanks for the help.
