### ISSUE TITLE
hbase-indexer cant convert numberic column to solr numberic field ???

### ISSUE THREAD

**Issue by finch0001** [NGDATA/hbase-indexer#80]
16/08/04 09:55:34 INFO api.MorphlineContext: Importing commands
16/08/04 09:55:34 INFO api.MorphlineContext: Done importing commands
16/08/04 09:55:34 WARN parse.ByteArrayValueMappers: Error mapping byte value 20 to int
java.lang.IllegalArgumentException: offset (0) + length (4) exceed the capacity of the array: 2
        at org.apache.hadoop.hbase.util.Bytes.explainWrongLengthOrOffset(Bytes.java:625)
        at org.apache.hadoop.hbase.util.Bytes.toInt(Bytes.java:795)
        at org.apache.hadoop.hbase.util.Bytes.toInt(Bytes.java:771)
        at com.ngdata.hbaseindexer.parse.ByteArrayValueMappers$1.mapInternal(ByteArrayValueMappers.java:37)
        at com.ngdata.hbaseindexer.parse.ByteArrayValueMappers$AbstractByteValueMapper.map(ByteArrayValueMappers.java:157)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$Mapping.extractWithSingleOutputField(ExtractHBaseCellsBuilder.java:204)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$Mapping.apply(ExtractHBaseCellsBuilder.java:197)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$ExtractHBaseCells.doProcess(ExtractHBaseCellsBuilder.java:83)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:161)
        at org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:186)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:161)
        at com.ngdata.hbaseindexer.morphline.LocalMorphlineResultToSolrMapper.map(LocalMorphlineResultToSolrMapper.java:242)
        at com.ngdata.hbaseindexer.morphline.MorphlineResultToSolrMapper.map(MorphlineResultToSolrMapper.java:145)
        at com.ngdata.hbaseindexer.indexer.Indexer$RowBasedIndexer.calculateIndexUpdates(Indexer.java:289)
        at com.ngdata.hbaseindexer.indexer.Indexer.indexRowData(Indexer.java:144)
        at com.ngdata.hbaseindexer.indexer.IndexingEventListener.processEvents(IndexingEventListener.java:99)
        at com.ngdata.sep.impl.SepEventExecutor$1.run(SepEventExecutor.java:97)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
16/08/04 09:56:05 INFO api.MorphlineContext: Importing commands
16/08/04 09:56:06 INFO api.MorphlineContext: Done importing commands
16/08/04 09:57:49 WARN parse.ByteArrayValueMappers: Error mapping byte value 0 to int
java.lang.IllegalArgumentException: offset (0) + length (4) exceed the capacity of the array: 1
        at org.apache.hadoop.hbase.util.Bytes.explainWrongLengthOrOffset(Bytes.java:625)
        at org.apache.hadoop.hbase.util.Bytes.toInt(Bytes.java:795)
        at org.apache.hadoop.hbase.util.Bytes.toInt(Bytes.java:771)
        at com.ngdata.hbaseindexer.parse.ByteArrayValueMappers$1.mapInternal(ByteArrayValueMappers.java:37)
        at com.ngdata.hbaseindexer.parse.ByteArrayValueMappers$AbstractByteValueMapper.map(ByteArrayValueMappers.java:157)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$Mapping.extractWithSingleOutputField(ExtractHBaseCellsBuilder.java:204)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$Mapping.apply(ExtractHBaseCellsBuilder.java:197)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$ExtractHBaseCells.doProcess(ExtractHBaseCellsBuilder.java:83)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:161)
        at org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:186)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:161)
        at com.ngdata.hbaseindexer.morphline.LocalMorphlineResultToSolrMapper.map(LocalMorphlineResultToSolrMapper.java:242)
        at com.ngdata.hbaseindexer.morphline.MorphlineResultToSolrMapper.map(MorphlineResultToSolrMapper.java:145)
        at com.ngdata.hbaseindexer.indexer.Indexer$RowBasedIndexer.calculateIndexUpdates(Indexer.java:289)
        at com.ngdata.hbaseindexer.indexer.Indexer.indexRowData(Indexer.java:144)
        at com.ngdata.hbaseindexer.indexer.IndexingEventListener.processEvents(IndexingEventListener.java:99)
        at com.ngdata.sep.impl.SepEventExecutor$1.run(SepEventExecutor.java:97)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
16/08/04 09:58:16 INFO api.MorphlineContext: Importing commands
16/08/04 09:58:16 INFO api.MorphlineContext: Done importing commands
16/08/04 09:58:16 WARN parse.ByteArrayValueMappers: Error mapping byte value 0 to int
java.lang.IllegalArgumentException: offset (0) + length (4) exceed the capacity of the array: 1
        at org.apache.hadoop.hbase.util.Bytes.explainWrongLengthOrOffset(Bytes.java:625)
        at org.apache.hadoop.hbase.util.Bytes.toInt(Bytes.java:795)
        at org.apache.hadoop.hbase.util.Bytes.toInt(Bytes.java:771)
        at com.ngdata.hbaseindexer.parse.ByteArrayValueMappers$1.mapInternal(ByteArrayValueMappers.java:37)
        at com.ngdata.hbaseindexer.parse.ByteArrayValueMappers$AbstractByteValueMapper.map(ByteArrayValueMappers.java:157)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$Mapping.extractWithSingleOutputField(ExtractHBaseCellsBuilder.java:204)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$Mapping.apply(ExtractHBaseCellsBuilder.java:197)
        at com.ngdata.hbaseindexer.morphline.ExtractHBaseCellsBuilder$ExtractHBaseCells.doProcess(ExtractHBaseCellsBuilder.java:83)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:161)
        at org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:186)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:161)
        at com.ngdata.hbaseindexer.morphline.LocalMorphlineResultToSolrMapper.map(LocalMorphlineResultToSolrMapper.java:242)
        at com.ngdata.hbaseindexer.morphline.MorphlineResultToSolrMapper.map(MorphlineResultToSolrMapper.java:145)
        at com.ngdata.hbaseindexer.indexer.Indexer$RowBasedIndexer.calculateIndexUpdates(Indexer.java:289)
        at com.ngdata.hbaseindexer.indexer.Indexer.indexRowData(Indexer.java:144)
        at com.ngdata.hbaseindexer.indexer.IndexingEventListener.processEvents(IndexingEventListener.java:99)
        at com.ngdata.sep.impl.SepEventExecutor$1.run(SepEventExecutor.java:97)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by gabrielreid** [comment]
This is an issue with mapping a two-byte byte array (containing bytes 0x50 and 0x48, or ascii characters '2' and '0') into an integer value, which requires four bytes. In other words, it looks like there is an HBase cell containing these two bytes which is configured to be interpreted as an integer, which therefore doesn't work and results in this logging.

The "20" in the log message "Error mapping byte value 20 to int" is admittedly misleading, but it's the result of HBase's Bytes.toStringBinary method, which is very useful for non-ascii characters, but maps ascii characters to their ascii character values.
