### ISSUE TITLE
Update code to upstream solr-6.2

### ISSUE THREAD

**Issue by whoschek** [NGDATA/hbase-indexer#82]

**Comment by whoschek** [comment]
I'll submit a corresponding pull request shortly.

**Comment by janvanbesien** [comment]
I saw some integration test failures with this branch (could be due to one of my earlier commits). In particular some tests related to morphlines.

Failed tests: 
  HBaseMapReduceIndexerToolGoLiveTest.testIndexer_Morphlines:281 expected:<0> but was:<-1>
  HBaseMapReduceIndexerToolTest.testIndexer_Morphlines:147 expected:<0> but was:<-1>

I saw this in the mapreduce logs (not 100% sure it is related), so maybe it is only a matter of configuration.

2016-09-05 11:19:33,341 INFO [IPC Server handler 9 on 48078] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Diagnostics report from attempt_1473074187230_0005_r_000000_0: Error: java.io.IOException: org.apache.solr.common.SolrException: Error opening new searcher. exceeded limit of maxWarmingSearchers=2, try again later.
        at org.apache.solr.hadoop.SolrRecordWriter.close(SolrRecordWriter.java:286)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: org.apache.solr.common.SolrException: Error opening new searcher. exceeded limit of maxWarmingSearchers=2, try again later.
        at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1792)
        at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1552)
        at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:650)
        at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:93)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:61)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1646)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1623)
        at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processCommit(LogUpdateProcessorFactory.java:160)
        at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:68)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:62)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:154)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2089)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
        at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:484)
        at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:501)
        at org.apache.solr.hadoop.BatchWriter.close(BatchWriter.java:212)
        at org.apache.solr.hadoop.SolrRecordWriter.close(SolrRecordWriter.java:274)
        ... 8 more

**Comment by whoschek** [comment]
@janvanbesien Interesting. So far I haven't seen this error in our jenkins runs. Seems spurious. I have now added a work-around commit that increases maxWarmingSearchers from 2 to maxWarmingSearchers in solrconfig.xml. Please retry with that and let me know.
